-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

CREATE TYPE "VerificationVerdict" AS ENUM ('GROUNDED', 'REVIEW', 'FLAGGED');
CREATE TYPE "ApiKeyStatus" AS ENUM ('ACTIVE', 'REVOKED');

CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "name" TEXT, "passwordHash" TEXT, "emailVerified" TIMESTAMP(3), "image" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Account" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "type" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerAccountId" TEXT NOT NULL, "refresh_token" TEXT, "access_token" TEXT, "expires_at" INTEGER, "token_type" TEXT, "scope" TEXT, "id_token" TEXT, "session_state" TEXT, CONSTRAINT "Account_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL, "sessionToken" TEXT NOT NULL, "userId" TEXT NOT NULL, "expires" TIMESTAMP(3) NOT NULL, CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VerificationToken" ("identifier" TEXT NOT NULL, "token" TEXT NOT NULL, "expires" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Organization" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Organization_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrganizationMember" ("id" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'member', "userId" TEXT NOT NULL, "organizationId" TEXT NOT NULL, CONSTRAINT "OrganizationMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ApiKey" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "prefix" TEXT NOT NULL, "secretHash" TEXT NOT NULL, "status" "ApiKeyStatus" NOT NULL DEFAULT 'ACTIVE', "lastUsedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "revokedAt" TIMESTAMP(3), "organizationId" TEXT NOT NULL, CONSTRAINT "ApiKey_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VerificationSession" ("id" TEXT NOT NULL, "externalId" TEXT NOT NULL, "prompt" TEXT NOT NULL, "response" TEXT NOT NULL, "trust" DOUBLE PRECISION NOT NULL, "verdict" "VerificationVerdict" NOT NULL, "result" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "organizationId" TEXT NOT NULL, "apiKeyId" TEXT, CONSTRAINT "VerificationSession_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId"); CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken"); CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token"); CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token"); CREATE UNIQUE INDEX "Organization_slug_key" ON "Organization"("slug"); CREATE UNIQUE INDEX "OrganizationMember_userId_organizationId_key" ON "OrganizationMember"("userId", "organizationId"); CREATE UNIQUE INDEX "ApiKey_secretHash_key" ON "ApiKey"("secretHash"); CREATE INDEX "ApiKey_organizationId_status_idx" ON "ApiKey"("organizationId", "status"); CREATE UNIQUE INDEX "VerificationSession_externalId_key" ON "VerificationSession"("externalId"); CREATE INDEX "VerificationSession_organizationId_createdAt_idx" ON "VerificationSession"("organizationId", "createdAt");

ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "OrganizationMember" ADD CONSTRAINT "OrganizationMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "OrganizationMember" ADD CONSTRAINT "OrganizationMember_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ApiKey" ADD CONSTRAINT "ApiKey_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "VerificationSession" ADD CONSTRAINT "VerificationSession_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "VerificationSession" ADD CONSTRAINT "VerificationSession_apiKeyId_fkey" FOREIGN KEY ("apiKeyId") REFERENCES "ApiKey"("id") ON DELETE SET NULL ON UPDATE CASCADE;
