var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/system-health/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1pdq98n._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jj_y02._.js")
R.c("server/chunks/ssr/[root-of-the-server]__112mz-6._.js")
R.c("server/chunks/ssr/_1f6o6wv._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/1oju_platform__next-internal_server_app_dashboard_system-health_page_actions_0850_00.js")
R.m(83939)
module.exports=R.m(83939).exports
